module.exports = {
  REQUEST_URL: 'https://nlftp.mlit.go.jp/ksj/gml/data/P20/P20-12/',
  REQUEST_EXTENSION: '.zip',
  FILE_PREFIX: 'P20-12_',
  FILE_SUFFIX: '_GML',
  FILE_EXTENSION: '.dbf',
  PREFECTURES: {
    HOKKAIDOU: ['01', false],
    AOMORI: ['02', false],
    IWATE: ['03', false],
    MIYAGI: ['04', false],
    AKITA :[ '05', false],
    YAMAGAT: ['06', false],
    FUKUSHIMA: ['07', false],
    IBARAKI: ['08', false],
    TOCHIGI: ['09', false],
    GUNMA: ['10', false],
    SAITAMA: ['11', false],
    CHIBA: ['12', false],
    TOKYO: ['13', false],
    KANAGAWA: ['14', false],
    NIIGATA: ['15', false],
    TOYAMA: ['16', false],
    ISHIKAWA: ['17', false],
    FUKUI: ['18', false],
    YAMANASHI: ['19', false],
    NAGANO: ['20', false],
    GIFU: ['21', true],
    SHIZUOKA: ['22', false],
    AICHI: ['23', false],
    TRIPLE: ['24', false],
    SHIGA: ['25', false],
    KYOTO: ['26', false],
    OSAKA: ['27', false],
    HYOGO: ['28', false],
    NARA: ['29', false],
    WAKAYAMA: ['30', false],	
    TOTTORI: ['31', false],
    SHIMANE: ['32', false],
    OKAYAMA: ['33', false],
    HIROSHIMA: ['34', false],
    YAMAGUCHI: ['35', false],
    TOKUSHIMA: ['36', false],
    KAGAWA: ['37', false],
    EHIME: ['38', false],
    KOCHI: ['39', false],
    FUKUOKA: ['40', false],
    SAGA: ['41', false],
    NAGASAKI: ['42', false],
    KUMAMOTO: ['43', false],
    OITA: ['44', false],
    MIYAZAKI: ['45', false],
    KAGOSHIMA: ['46', false],	
    OKINAWA: ['47', false]
  },
  SHEET_NAME: 'Sheet1'
}
